#!/bin/bash

if [ ! -d ../data ] ; then
	echo "Must run $0 from scripts/ directory" > /dev/stderr
	exit 1
fi

cd ../data
mkdir -p ../output

../scripts/foldmason_msa2lddt.bash BB11001.afa BB11001.files \
  > ../output/foldmason_BB11001.txt
